apiVersion: networking.gloo.solo.io/v2
kind: RouteTable
metadata:
  name: productpage-route-table
  namespace: web-frontend-team
  labels:
    # To auto export
    # workspace.solo.io/exported: "true"
    exposeResource: "true"
spec:
  workloadSelectors: []
  http:
    - name: productpage
      matchers:
        - uri:
            exact: /productpage
        - uri:
            prefix: /static
        - uri:
            exact: /login
        - uri:
            exact: /logout
        - uri:
            prefix: /api/v1/products
      forwardTo:
        destinations:
          - ref:
              name: productpage
              namespace: bookinfo-frontends
              cluster: west-mesh
            port:
              number: 9080