apiVersion: admin.gloo.solo.io/v2
kind: WorkspaceSettings
metadata:
  name: backend-apis-team-settings
  namespace: backend-apis-team
spec:
  exportTo:
    - workspaces:
      - name: web-frontend-team
      resources:
        - kind: ROUTE_TABLE
        - kind: SERVICE
        - kind: VIRTUAL_DESTINATION
  options:
    eastWestGateways:
      - selector:
          labels:
            istio: eastwestgateway
    federation:
      # Explicitly disable in favor of VD
      enabled: false
    serviceIsolation:
      enabled: true
      trimProxyConfig: true