apiVersion: networking.gloo.solo.io/v2
kind: RouteTable
metadata:
  name: main
  namespace: ops-team
spec:
  hosts:
    - '*'
  virtualGateways:
    - name: north-south-gateway
      namespace: ops-team
      cluster: mgmt-mesh
  workloadSelectors: []
  http:
    - name: main
      matchers:
        - uri:
            prefix: /
      delegate:
        routeTables:
          - labels:
              exposeResource: "true"
        sortMethod: ROUTE_SPECIFICITY