apiVersion: networking.gloo.solo.io/v2
kind: VirtualGateway
metadata:
  name: north-south-gateway
  namespace: ops-team
spec:
  workloads:
    - selector:
        labels:
          istio: ingressgateway
        namespace: istio-ingress
        cluster: west-mesh
  listeners: 
    - http: {}
      port:
        number: 443
      tls:
        parameters:
          minimumProtocolVersion: TLSv1_3
        mode: SIMPLE
        secretName: north-south-gateway-tls
      allowedRouteTables:
        - host: '*'
          selector:
            workspace: ops-team