apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: north-south-gateway-tls-cert
  namespace: istio-ingress
  annotations:
    argocd.argoproj.io/sync-options: Prune=false, Delete=false
spec:
  secretName: north-south-gateway-tls
  commonName: apps.demo-gloo.apidays.apac.fe.gl00.net
  dnsNames:
    - apps.demo-gloo.apidays.apac.fe.gl00.net
  issuerRef:
    name: global-letsencrypt-cert-issuer
    kind: ClusterIssuer